export const data = [
  {
    id: 1,
    image: "../public/product1.png",
    title: "Эмаль Condor ПФ-115 жёлтая 1,8 кг",
    desc: "Быстросохнущая, высокоукрывистая, защита от водорослей, мха, лишайника, защита от грибка",
    count: 0,
    price: 234,
    isLiked: false,
    isSelected: false,
    toBasket: false,
  },
  {
    id: 2,
    image: "../public/product1.png",
    title: "Эмаль Condor ПФ-115 жёлтая 1,8 кг",
    desc: "Быстросохнущая, высокоукрывистая, защита от водорослей, мха, лишайника, защита от грибка",
    count: 0,
    price: 5456,
    isLiked: false,
    toBasket: false,
  },
  {
    id: 3,
    image: "../public/product1.png",
    title: "Эмаль Condor ПФ-115 жёлтая 1,8 кг",
    desc: "Быстросохнущая, высокоукрывистая, защита от водорослей, мха, лишайника, защита от грибка",
    count: 0,
    price: 234,
    isLiked: false,
    toBasket: false,
  },
  {
    id: 4,
    image: "../public/product1.png",
    title: "Эмаль Condor ПФ-115 жёлтая 1,8 кг",
    desc: "Быстросохнущая, высокоукрывистая, защита от водорослей, мха, лишайника, защита от грибка",
    count: 0,
    price: 500,
    isLiked: false,
    toBasket: false,
  },
];
